image: node:22.5
 
stages:
  - build
 
cache:
  paths:
    - node_modules/
 
before_script:
  - npm install
 
build_app:
  stage: build
  script:
    - npm run build --prod
  artifacts:
    paths:
      - dist/
    expire_in: 1 week


# Docker Build stage: Build and push Docker image to GitLab Container Registry
# docker_build:
#   image: docker:24.0.5
#   stage: docker_build
#   services:
#     - docker:24.0.5-dind
#   script:
#     # Log in to the GitLab Container Registry
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#     # Build the Docker image
#     - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
#     # Push the Docker image to the GitLab Container Registry
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# # Deploy stage: Deploy the application to OpenShift
# deploy:
#   image: registry.access.redhat.com/openshift3/oc:latest
#   stage: deploy
#   script:
#     - oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify
#     - oc project $OPENSHIFT_PROJECT
#     - oc new-app $DOCKER_REGISTRY/$DOCKER_PROJECT/angular-app:$CI_COMMIT_SHORT_SHA
#     - oc expose svc/angular-app
#     - oc rollout status dc/angular-app
